### ISSUE TITLE
Question Concerning Node.appkeys.count returning 0

### ISSUE THREAD

**Issue by deverickasih** [NordicSemiconductor/IOS-nRF-Mesh-Library#195]
Hi, i tried binding an appkey to a node :
```
try MeshNetworkManager.instance.send(ConfigAppKeyAdd(applicationKey: selectedAppKey), to: node)
```
it return successfully : 
```
MessageHandle(opCode: 0, source: 1, destination: 2, manager: Optional(nRFMeshProvision.MeshNetworkManager))
```
Then i tried to get the node and also placed a breakpoint after the following line of code :
```
let nodeToSend = MeshNetworkManager.instance.meshNetwork?.node(withAddress: node.unicastAddress)
```
When i checked the variable 'nodeToSend', the 'nodeToSend.appKeys' has 0 appkeys
Then when i try to get the list of applicationkeys with the following code :
```
let keysForNode : [ApplicationKey]! = selectedModel.parentElement?.parentNode?.applicationKeysAvailableFor(selectedModel)
```
keysForNode has no application keys..

I debugged this also with the project from master with code :
```
start("Adding Application Key...") {
        return try MeshNetworkManager.instance.send(ConfigAppKeyAdd(applicationKey: selectedAppKey), to: self.node)
}
```
when i checked self.node.appkeys.count using breakpoint, i get 0 after binding an appkey to it..

**Question**
Shouldn't there be at least one appkey since i have previously binded one?

What i planned on doing is after binding the appkey to node, i also want to immediately bind appkey to models inside the node with the following lines of code :
```
let message = ConfigModelAppBind(applicationKey: keysForNode[0], to: selectedModel)
try MeshNetworkManager.instance.send(message, to: selectedModel)
```
but keysForNode.count == 0 :(

**Comment by philips77** [comment]
All those methods you call are asynchronous. Adding an App Key to a Node requires active proxy connection to the mesh network, the `transmitter` and `bearer.delegate` set correctly, etc. You will always get the `MessageHandle` immediately, as this can be used to cancel the pending request. But this does not mean that the Node has already received the key. You need to wait for the `ConfigAppKeyStatus` message in manager's delegate. When you receive it, and the status is success, the Node has received the key and the local database has been updated, so since then requesting app keys for this node will return it.

**Comment by philips77** [comment]
In the sample app you have to put a breakpoint in the `meshNetworkManager(_:didReceiveMessage:sentFrom:to)` where the `ConfigAppKeyStatus` is received.

**Comment by deverickasih** [comment]
Thanks for this insight!
