### ISSUE TITLE
Swift compiler Error : Use of undeclared type 'OpenSSLHelper'

### ISSUE THREAD

**Issue by VR-123** [NordicSemiconductor/IOS-nRF-Mesh-Library#23]
**Describe the bug**
Install pod in our project give swift compiler Error i.e **Use of undeclared type 'OpenSSLHelper'** also run command **install pod** in your example project gives same error. can you please check it.

**Platform details:**
 - Device:  iPhone6
 - OS: iOS 11.2
 - Xcode : 9.2

**Comment by mostafaberg** [comment]
Good evening @VR-123 !

This is due to the fact that we haven't released this as a pod yet so we haven't tested all capabilities.

OpenSSL is a special case as it's a static library and that causes some issues with CocoaPods that we will address soon.

Which `pod` binary version are you using ? and also note that this running `pod install` will pull down OpenSSL and compile it, which will take a quite long time depending on your computer.

So what I would do is clear up all your work, pull the master/dev branch and open the example's workspace.

if you need to build this as a library into your own app, you'll need to add OpenSSL as a dependency to your project, and modify our pod spec file to remove OpenSSL as a dependency then pod install and wait for it to work:)

**Comment by VR-123** [comment]
Thanks for your feedback,
we are using pod binary version 1.4.0
now we are using your example's workspace for testing.

**Comment by mostafaberg** [comment]
No problems :), we are using pod 1.4.0 too so we're on the same page :)
if you are running directly from the master branch in the example workspace you shouldn't need to do any pod installation, as everything is already committed :)

are you still experiencing issues ?

**Comment by VR-123** [comment]
Hello,
We are still facing this issue but for now we have added nRFMeshProvision library Manually in our project when you released your pod then we added  library using pod in our project.

Thanks for your reply.

**Comment by mostafaberg** [comment]
Perfect, i'll keep this issue open until we have a Cocoapod release so you'll be notified !, thanks for your patience :)

**Comment by mostafaberg** [comment]
Resolved in 1.0.4 now :),
you may try the pod directly by running the `pod try nRFMeshProvision` command in your terminal ! thanks for waiting:)
