### ISSUE TITLE
Connect Proxy with node UUID

### ISSUE THREAD

**Issue by Baothien1301** [NordicSemiconductor/IOS-nRF-Mesh-Library#245]
Hello!
Please help me! When i scan node in order to connect proxy, I recieve a list peripheral with advertisment data. I want to connect to a node with UUID. But scanning UUID and node UUID are difference.
And how i connect proxy to a node with UUID or unicast address?

**Comment by philips77** [comment]
Provisioned mesh nodes may be configured to advertise with "Node identity". This is what the spec says:

> 7.2.2.2.3 Advertising with Node Identity
Advertising using the Node Identity is used to identify a node based on the unicast address of the primary element and the network key of a subnet to which the node belongs. This can be useful when large amounts of data need to be delivered to a node via GATT for cases when the node cannot be easily identified or is not advertising. This advertisement may be used to initiate a GATT connection to the selected node.
If PB-GATT is supported and Mesh Proxy Service is exposed, immediately after provisioning is completed using PB-GATT (see Section 5.2.2), the Mesh Proxy Service shall start advertising with Node Identity using the provisioned network.
When the server starts advertising as a result of user interaction, the server shall interleave the advertising of each subnet it is a member of. When the server starts advertising as a result of the Node Identity state being enabled, the server shall only advertise using the subnet that it was enabled on. The duration of advertising in these two cases is limited to 60 seconds.

From the Node Identity Beacon you may get its Unicast Address.

The UUID you get from CBPeripheral is a completely different thing. It's a identifier that iOS uses instead of MAC address for privacy reasons. The UUID of the mesh node is taken from the Unprovisioned Device beacon.
