### ISSUE TITLE
NetworkConnection maxConnections

### ISSUE THREAD

**Issue by fiveagle** [NordicSemiconductor/IOS-nRF-Mesh-Library#252]
Hi,

I'm using the class NetworkConnection from the sample app. 
It has a property maxConnections that limits the number of open bearers.
Since my app is planned to create a mesh with up to 64 devices, it is necessary to set maxConnections to 65 (64 + the provisioner)?

Thanks.

**Comment by philips77** [comment]
No, `maxConnections` can control how many GATT proxies the iPhone can connect to simultaneously. It will still be sending messages only through the first one, but can receive from all (it shouldn't due to Filter Proxy, I think). The intention of introducing it was to allow quick switching proxy when one gets disconnected. Then there's no need to scan and connect to another one, as it's already connected. But this feature has not been tested, actually, so I don't know if e.g. the proxy filter gets configured when1st proxy disconnects. Keep `maxConnections` to 1 or max 3.
