### ISSUE TITLE
Mesh Spec JSON Gives 404

### ISSUE THREAD

**Issue by horsejockey** [NordicSemiconductor/IOS-nRF-Mesh-Library#267]
In the code a mesh json spec is referenced but it gives a 404.  It appears in [MeshNetwork.swift](https://github.com/NordicSemiconductor/IOS-nRF-Mesh-Library/blob/45e12224e8b5f2d45659e99dddda966b1ba17789/nRFMeshProvision/Classes/Mesh%20Model/MeshNetwork.swift#L113)

Here is the URL:
http://www.bluetooth.com/specifications/assigned-numbers/mesh-profile/cdb-schema.json#

Is that supposed to reference a specification for storing a mesh network as JSON. I was hoping there was a standard I could use for the API I am writing.

**Comment by philips77** [comment]
The standard is still being finalized. In version 2.3 and perhaps later we plan to update the schema to match the changes introduced since the current version was developed. Until it's final, we recommend not to relay on what's in the app. Unfortunately I can't say much more. We will make sure to ensure proper migration of existing json files in the upcoming versions.
