### ISSUE TITLE
How does the Alexa and the app control the devices

### ISSUE THREAD

**Issue by liushuangddu** [NordicSemiconductor/IOS-nRF-Mesh-Library#336]
Hi, As you see, I have a Amazon echo  the amazon can control the device, and my self app also. but firstly I use amazon provisioned the device  then my app cannot control the device. so how could I do that

**Comment by philips77** [comment]
Hi,
You'd have to export mesh network configuration from Amazon Echo device. I don't know how that can be done, or is it possible, can't help you here. Then, you can import the configuration to nRF Mesh. If the exported format is different from what nRF Mesh supports, you need to export a dummy config from nRF Mesh, open on PC and modify with data from Alexa, and import again.  Most important is to have the network keys, app keys, nodes (with proper addresses and device keys) in place, so that both Alexa and nRF Mesh could communicate with the same network.
