### ISSUE TITLE
Questions about elements and models

### ISSUE THREAD

**Issue by trusbe** [NordicSemiconductor/IOS-nRF-Mesh-Library#349]
May I ask the latest version of SDK, when the same hardware device (RGBWC light) needs to support OnOff, HSL, CTL control, can one element be used, including these three models at the same time, when sending the OnOff message, I hope that all the LEDs will be Respond to the OnOff message, but now only the CTL（WC） or HSL（RGB） LED will respond, not all of them. Is it necessary to use multiple elements? 

The firmware uses the latest version of the NCS SDK. What should we do to achieve the desired effect?

Thanks a lot!

**Comment by philips77** [comment]
Hello,
As the issue you have is not directly related to the mesh library for iOS, but more a generic one, consider asking it on [DevZone](https://devzone.nordicsemi.com/). You'll get a response from our Support Team which can handle those kind of questions, leaving the issues here only for mobile implementation issues.

Answering your question quickly, you cannot have more than one instance of the same model on one element. You need to read how the models you have are bound to one another. You'd use multiple elements when you have multiple lights on a device, each element controlling a single light. Sometimes, however, you need another element to accommodate a model that cannot be added to the previous element due to the above-mentioned restriction. But you should find more complete answer on DevZone. You may also read the Mesh Model spec here: https://www.bluetooth.com/specifications/specs/?status=active&keyword=mesh, which describes how models should be bound to each other.
