### ISSUE TITLE
How to set up a relay node?

### ISSUE THREAD

**Issue by okappi0258** [NordicSemiconductor/IOS-nRF-Mesh-Library#370]
I am building a system to change the color of some LEDs 30 meters away outdoors.
However, there are times when the color does not change, and the message sending or receiving fails.
So, I would like to use the relay function to stabilize the transmission and reception, but I don't know how to set it up.
I would appreciate it if you could let me know.

**Comment by okappi0258** [comment]
I understood it somewhat.
Now we are configuring the Publication settings in ConfigModelPublicationSet. Is there any way to stabilize the communication at a remote location outdoors other than the relay function or ConfigModelPublicationSet?

**Comment by philips77** [comment]
With mesh config messages you only may increase statistical chances of a successful transfer, as you just set number of transmissions.
You could make use of acknowledged messages, but that may generate a lot of traffic when sent to multiple nodes (group address), so that's not recommended. For messages sent to a unicast address you may also set them as segmented, so they'll be ack-ed on lower transport layer and resent, if needed. But in general, publish retransmit, network transmit and relay config should be sufficient. It's just difficult to set proper values, and even those don't guarantee a success, just increase chances of a success.

**Comment by philips77** [comment]
Also, initially try with smaller values, not 7.  Even few retransmits should help without making huge traffic.

**Comment by philips77** [comment]
> Does the decodable message include GenericOnOffSet message?

Any message can be relayed. The Relay Node needs to decode the message to decrement TTL value. If the TTL is greater or equal to 2 it encodes the message again and transmits. For this purpose it needs to know the Network Key, which the message was encoded with on Network Layer. It doesn't need to know Application Key, as the message is only processed by Network Layer. See chapter 3.11 (Message processing flow) in Mesh Profile 1.0.1.

> Also, I tried sending a `ConfigRelaySet` message, but the LED goes out.
Does the firmware need to be configured to receive `ConfigRelaySet` messages as well?

The firmware must support Relay feature. You get it in the Composition Data. I don't know what the LED indicates in your case. The Config Server model on any device should support `ConfigRelaySet` message. If relay feature is not supported, it should reply with status "not supported". See chapter 4.3.2.14 and 4.2.8 in Mesh Profile 1.0.1.

**Comment by okappi0258** [comment]
I understand.
I was able to send the ConfigRelaySet message, but I am struggling with the firmware side settings.

**Comment by philips77** [comment]
Yes it does.

I'm closing the issue as it has been solved, I believe.
