### ISSUE TITLE
How can I forcibly delete a node device from the network?

### ISSUE THREAD

**Issue by trusbe** [NordicSemiconductor/IOS-nRF-Mesh-Library#42]
Hi, I have a question：
If a device is already in the network, I manually reset it，
How do I remove it from ：
`let nodes = meshManager.stateManager().state().provisionedNodes? `
Need to delete manually?

Thank you .

**Comment by mostafaberg** [comment]
Hi @trusbe, sorry for the late response!

yes you have to remove it manually for the time being, unfortunately there are some missing parts in the SDK that has been worked around by implementing the features in the example app instead, those lacking parts will be fixed in the near future!, will keep the issue opened till we fix that part at least so you'll get an update, till then, you'll have to manually remove your own nodes from the state.

**Comment by trusbe** [comment]
@mostafaberg  Ok, wait for the follow-up update，  thank you for your reply.

**Comment by philips77** [comment]
Closing the issue as the old version is no longer maintained.
